# OAuth2なしのRundeck HA最小構成（認証デバッグ用）
services:
  nginx:
    image: nginx:alpine
    ports:
      - "9000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - oauth-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    environment:
      - PORT=8080
    networks:
      - oauth-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database for Rundeck HA
  rundeck-postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=rundeck
      - POSTGRES_USER=rundeck
      - POSTGRES_PASSWORD=rundeck123
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --locale=C
    volumes:
      - rundeck-postgres-data:/var/lib/postgresql/data
    networks:
      - oauth-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rundeck -d rundeck"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Rundeck Active Node
  rundeck-active:
    image: rundeck/rundeck:5.14.0-20250804
    ports:
      - "4444:4440"
    environment:
      - RUNDECK_GRAILS_URL=http://localhost:9000/rundeck
      - RUNDECK_SERVER_FORWARDED=true
      - RUNDECK_LOGGING_STRATEGY=CONSOLE
      - RUNDECK_DATABASE_DRIVER=org.postgresql.Driver
      - RUNDECK_DATABASE_USERNAME=rundeck
      - RUNDECK_DATABASE_PASSWORD=rundeck123
      - RUNDECK_DATABASE_URL=jdbc:postgresql://rundeck-postgres:5432/rundeck
      - RUNDECK_PLUGIN_PROVISIONING_ENABLED=true
      - RUNDECK_SERVER_UUID=e7dcae5b-7bbd-4169-bc44-ddd7ec0f3d1a
      - RUNDECK_QUARTZ_JOB_STORE_DELEGATE_CLASS=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      - RUNDECK_QUARTZ_JOB_STORE_CLASS=org.springframework.scheduling.quartz.LocalDataSourceJobStore
      - RUNDECK_QUARTZ_JOB_STORE_IS_CLUSTERED=true
      - RUNDECK_QUARTZ_JOB_STORE_CLUSTER_CHECKIN_INTERVAL=20000
      - RUNDECK_PREAUTH_ENABLED=true
      - RUNDECK_PREAUTH_ATTRIBUTE_NAME=REMOTE_USER_EMAIL
      - RUNDECK_PREAUTH_DELIMITER=,
      - RUNDECK_PREAUTH_USERNAME_HEADER=X-Auth-Request-Email
      - RUNDECK_PREAUTH_ROLES_HEADER=X-Auth-Request-Roles
      - RUNDECK_PREAUTH_REDIRECT_LOGOUT=http://localhost:9000/oauth2/sign_out
      - RUNDECK_PREAUTH_USER_FIRST_NAME_HEADER=X-Auth-Request-Given-Name
      - RUNDECK_PREAUTH_USER_LAST_NAME_HEADER=X-Auth-Request-Family-Name
      - GRAILS_ASSETS_MINIFIED=false
      - GRAILS_ASSETS_PLUGIN_BOOTSTRAP_ENABLED=false
      - RUNDECK_STATIC_ASSETS_PATH=/home/rundeck/user-assets
      - RUNDECK_GRAILS_SERVER_URL=http://localhost:9000/rundeck
    volumes:
      - rundeck-shared-data:/home/rundeck/server/data
      - ./rundeck/config:/home/rundeck/server/config
    depends_on:
      - rundeck-postgres
      - backend
    networks:
      - oauth-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4440/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Rundeck Standby Node
  rundeck-standby:
    image: rundeck/rundeck:5.14.0-20250804
    ports:
      - "4445:4440"
    environment:
      - RUNDECK_GRAILS_URL=http://localhost:9000/rundeck
      - RUNDECK_SERVER_FORWARDED=true
      - RUNDECK_LOGGING_STRATEGY=CONSOLE
      - RUNDECK_DATABASE_DRIVER=org.postgresql.Driver
      - RUNDECK_DATABASE_USERNAME=rundeck
      - RUNDECK_DATABASE_PASSWORD=rundeck123
      - RUNDECK_DATABASE_URL=jdbc:postgresql://rundeck-postgres:5432/rundeck
      - RUNDECK_PLUGIN_PROVISIONING_ENABLED=true
      - RUNDECK_SERVER_UUID=ffe48a7c-a882-4864-a2a3-c8842d1ed4e2
      - RUNDECK_QUARTZ_JOB_STORE_DELEGATE_CLASS=org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      - RUNDECK_QUARTZ_JOB_STORE_CLASS=org.springframework.scheduling.quartz.LocalDataSourceJobStore
      - RUNDECK_QUARTZ_JOB_STORE_IS_CLUSTERED=true
      - RUNDECK_QUARTZ_JOB_STORE_CLUSTER_CHECKIN_INTERVAL=20000
      - RUNDECK_PREAUTH_ENABLED=true
      - RUNDECK_PREAUTH_ATTRIBUTE_NAME=REMOTE_USER_EMAIL
      - RUNDECK_PREAUTH_DELIMITER=,
      - RUNDECK_PREAUTH_USERNAME_HEADER=X-Auth-Request-Email
      - RUNDECK_PREAUTH_ROLES_HEADER=X-Auth-Request-Roles
      - RUNDECK_PREAUTH_REDIRECT_LOGOUT=http://localhost:9000/oauth2/sign_out
      - RUNDECK_PREAUTH_USER_FIRST_NAME_HEADER=X-Auth-Request-Given-Name
      - RUNDECK_PREAUTH_USER_LAST_NAME_HEADER=X-Auth-Request-Family-Name
      - GRAILS_ASSETS_MINIFIED=false
      - GRAILS_ASSETS_PLUGIN_BOOTSTRAP_ENABLED=false
      - RUNDECK_STATIC_ASSETS_PATH=/home/rundeck/user-assets
      - RUNDECK_GRAILS_SERVER_URL=http://localhost:9000/rundeck
    volumes:
      - rundeck-shared-data:/home/rundeck/server/data
      - ./rundeck/config:/home/rundeck/server/config
    depends_on:
      - rundeck-postgres
      - backend
    networks:
      - oauth-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4440/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  rundeck-postgres-data:
  rundeck-shared-data:

networks:
  oauth-network:
    driver: bridge
