# 軽量OIDC Providerを使ったローカルOAuth2設定
services:
  # Simple OIDC Provider
  oidc-provider:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./oidc-provider:/app
    networks:
      - oauth-network
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - ISSUER=http://localhost:3000
      - PORT=3000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/.well-known/openid-configuration"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # OAuth2 Proxy - OIDC Provider用設定
  oauth2-proxy-oidc:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    environment:
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_OIDC_ISSUER_URL=http://oidc-provider:3000
      - OAUTH2_PROXY_CLIENT_ID=rundeck
      - OAUTH2_PROXY_CLIENT_SECRET=rundeck-secret
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_UPSTREAM=http://backend:8080
      - OAUTH2_PROXY_HTTP_ADDRESS=0.0.0.0:4180
      - OAUTH2_PROXY_REDIRECT_URL=http://localhost:9000/oauth2/callback
      - OAUTH2_PROXY_COOKIE_SECURE=false
      - OAUTH2_PROXY_COOKIE_HTTPONLY=true
      - OAUTH2_PROXY_SET_XAUTHREQUEST=true
      - OAUTH2_PROXY_PASS_ACCESS_TOKEN=true
      - OAUTH2_PROXY_PASS_USER_HEADERS=true
      - OAUTH2_PROXY_SCOPE=openid email profile
      - OAUTH2_PROXY_COOKIE_SECRET=VHYjkHPUrFYM8w8SG3BVnCJfKxBS61JF
      - OAUTH2_PROXY_SKIP_OIDC_DISCOVERY=false
      - OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL=true
    depends_on:
      - oidc-provider
      - backend
    networks:
      - oauth-network
    restart: unless-stopped

networks:
  oauth-network:
    driver: bridge