
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK
repositories:
  - repositoryName: official
    enabled: true
    type: HTTP
    owner: RUNDECK